sudo: required
dist: trusty
group: edge

language: erlang

services:
  - docker

otp_release:
  - 19.1
  - 20.0
  - 20.1
  - 21.0

install: wget https://github.com/erlang/rebar3/releases/download/3.6.2/rebar3 && chmod 755 rebar3

script: ./rebar3 update && ./rebar3 ct && ./rebar3 dialyzer && ./rebar3 coveralls send

cache:
  directories:
  - $HOME/.cache/rebar3/

addons:
  apt:
    packages:
      - libevent-dev
