sudo: required
dist: xenial
group: edge

language: erlang

install:
  - ORIG_DIR=$PWD
  - CURL_VERSION=7.71.1
  - wget https://github.com/erlang/rebar3/releases/download/3.10.0/rebar3 && chmod 755 rebar3
  - wget https://curl.haxx.se/download/curl-$CURL_VERSION.tar.gz && tar xf curl-$CURL_VERSION.tar.gz
  - cd curl-$CURL_VERSION && ./configure && make && sudo make install
  - cd $ORIG_DIR

otp_release:
  - 22.3.4
  - 23.0

script:
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
  - ./rebar3 update && ./rebar3 ct && ./rebar3 dialyzer && ./rebar3 coveralls send

before_install:
  - sudo ifconfig
  - sudo apt-get update -q
  - sudo apt-get install -qy build-essential libssl-dev libnghttp2-dev

cache:
  directories:
    - $HOME/.cache/rebar3/

addons:
  apt:
    packages:
      - libevent-dev
